MonoGame/docs.monogame.github.io

articles/preparing_for_consoles.md
Just added some recommendations of parsing libraries for consoles as this a very common pitfall that I've seen when porting games.
=> Added parsing libraries recommendations

articles/getting_started/1_setting_up_your_development_environment_unix.md
The WINE setup scripts were moved to be hosted on the website. This updates the url in the documentation.
Reference:
- https://github.com/MonoGame/monogame.github.io/pull/134
=> Updates the url for WINE Setup Script

.github/workflows/main.yml, .github/workflows/pullrequest.yml, api/index.md, articles/getting_started/1_setting_up_your_development_environment_windows.md, articles/toc.yml, docfx.json
This PR updates the `docfx.json` configuration file to add a rule set that will force a build error if there is an invalid link or uid ref detected on build.
> [!WARNING]
> The CI of this PR is going to fail due to invalid UID refs and links.  That means this PR is doing what it's supposed to do. Those issues should be resolved in a separate PR.
https://github.com/MonoGame/docs.monogame.github.io/issues/11
=> Treat Invalid Links as Errors

README.md, articles/monogame/howto/audio/HowTo_ChangePitchAndVolume.md, articles/monogame/howto/content_pipeline/HowTo_Add_XML.md, articles/monogame/howto/graphics/HowTo_Create_a_RenderTarget.md, articles/monogame/howto/graphics/HowTo_RenderModel.md, articles/monogame/whatis/content_pipeline/index.md, articles/monogame/whatis/index.md
- Updated the `HowTo_ChangePitchAndVolume.md` file to enhance readability and clarity of the code and instructions. 
- Changes include bold formatting for method and class names, added explanations for pitch and volume concepts, `using` statements, fields for sound effect and its properties, and modifications to the `Game.LoadContent` method. 
- Also included notes on sound looping, state checking, and usage of `MathHelper.Clamp` method. 
- Extended example added for key press detection and sound effect adjustment. 
- Updated the copyright year to 2024. The subproject commit in MonoGame has been updated to `81ed391a4d0fd81e3ee4bfe2492ad9a0e7f4cfc5`.
=> Updated Pull request targetting [Base]

articles/content_pipeline/custom_effects.md
This is to fix issue #19 
The (---) hr character is not always supported in markdown parsing and seems to be causing the issue here. It shows up good in VS and GitHub md preview, but is not making it into the html. Removing it actually seems to look okay as the generated tables have outlines and a good amount of spacing around them.
The asterisks were not breaking anything, but get printed as just literal asterisks. Not sure if that is intentional so I just removed them because it seems to look better and is easier to copy without them. Let me know if I should not have done that!
Here is a preview image:
=> Fix effect table by removing hrs and asterisks

articles/roadmap.md
Add the bounty in progress section for the Texture Compression work
=> Texture Compresison Bounty Roadmap

articles/migration/updating_versions.md, articles/toc.yml
With the release of version 3.8.2.1105 and the news that more frequent monthly releases will be coming, this documentation outlines the steps users would need to take to update their development environment and existing projects to the new version if they wish to.
=> Adds documentation for Updateing MonoGame

articles/console_access.md
I fixed some statements in the document and further clarified some things.
=> Fixed console access doc

articles/getting_started/packaging_games.md
Update the Packaging instructions for MacOS to include `PublishAot` and other improvements.
=> Update MacOS packaging_games.md

articles/getting_started/5_adding_basic_code.md
Cast `PlayerIndex.One` as int so it compiles. Also correct differences between example code in block and explanation.
=> Correct 5_adding_basic_code.md

articles/getting_started/index.md, articles/toc.yml
Some of the new articles do not appear on the site.
=> Update toc.yml to include Development Nuget Article

templates/monogame/public/main.css
This improves the whitespace in the doc site:
Before:
After:
Before:
After:
Fixes https://github.com/MonoGame/monogame.github.io/issues/146.
=> Improved whitespace

articles/getting_started/packaging_games.md
When using PublishAOT, even when making use of `TrimmerRootAssembly `, I still got warnings that look like:
This PR updates the docs to indicate this is normal.
=> Add note about PublishAOT and warnings

articles/getting_started/2_choosing_your_ide_visual_studio.md
Adds a warning to alert new users that the Visual Studio 2022 MonoGame extension has not been updated.
Based off of personal experience and this discord post from @AristurtleDev 
https://discord.com/channels/355231098122272778/402546044274999299/1293957422112575579
=> Adds a warning since the Visual Studio 2022 MonoGame extension is currently broken.

articles/getting_started/packaging_games.md
https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli
Incorrect name is used in docs - this PR updates to use the correct term `PublishSingleFile` instead of the incorrect `SingleFilePublish`.
=> Use correct term for PublishSingleFile

articles/getting_started/2_choosing_your_ide_rider.md
=> Fix Typo in 2_choosing_your_ide_rider.md

CONTRIBUTING.md, README.md, articles/contributing.md
I noticed that the [Contributing Guidelines](https://docs.monogame.net/articles/contributing) contained instructions on [generating the documentation site](https://docs.monogame.net/articles/contributing#generating-the-documentation-website) that was not consistent with this repo's readme.  So I updated the article to include the current steps needed to get the doc site running.
I also made some changes to improve the general readability of these guidelines. I mostly focused on reducing redundancy, adjusting flow, and explaining the purpose of certain sections. Here's an example of those changes.
=> Update Contribution Guidelines

docfx.json
Addresses issue #91
Turns on DocFX's search bar for the doc site. Here is an example of searching for `DepthStencilState` in my local doc site.
DocFX's search bar is powered by lunr.js and therefore is subject to the idiosyncrasies of this search engine as described in the [lunr docs](https://lunrjs.com/guides/searching.html). 
For example, lunr assumes each term in the search query is atomic. So searching for `graph` and `graphic` will yield different results. 
Additionally, lunr assumes a logical OR when searching with multiple terms. Therefore, searching `aspect ratio` will return the combined results of the two separate search queries for `aspect` and `ratio` but not for the specific phrase `aspect ratio`. This can be partially mitigated by using the search query `+aspect +ratio` but …
=> Add search bar

articles/getting_started/tools/mgfxc.md
At the end of page https://docs.monogame.net/articles/getting_started/tools/mgfxc.html there is the following code sample:
byte[] bytecode = File.ReadAllBytes("mycompiled.mgfx"); var effect = new Effect(bytecode);
It's is not working has the Effect class has no such constructor. The closest available constructor is Effect(GraphicsDevice graphicsDevice, byte[] effectCode).
- Resolves #84
=> Update mgfxc docs with the correct code sample

templates/monogame/layout/_master.tmpl, templates/monogame/partials/topnav.tmpl.partial, templates/monogame/public/injectDonateButton.js, templates/monogame/public/main.css
DocFX dynamically generates the navbar on the client side through the docfx.js code, it's not something that is statically rendered when the page is built.  In order for the Donate button to be placed to the left of the theme switch button like on the main monogame side, the Donate button needs to be injected after the page loads and then after the navbar is dynamically generated.
DocFX uses Bootstrap 3.4.1 while the main monogame website uses Bootstrap 5.3.2.  This adjusts the navbar container only to match the `max-width` value of the current bootstrap version that is used on the main site so that it appears more centered.
=> Navbar Adjustments

README.md, templates/monogame/layout/_master.tmpl, templates/monogame/partials/topnav.tmpl.partial, templates/monogame/public/injectDonateButton.js, templates/monogame/public/main.css, toc.yml
Moved Donate button and added link to Resources to the Nav Bar.
=> Add Resources and make Donate a button

LICENSE, docfx.json, templates/monogame/partials/footer.tmpl.partial
Small update to increment the footer year and change the copyright text on the license on this repo to match the MonoGame Foundation messaging used elsewhere.
=> Update footer year and license copyright

articles/getting_started/3_understanding_the_code.md
While going through the tutorial I noticed that it referred to Game.cs instead of the generated Game1.cs, so I corrected that. Also updated two code blocks to reflect the current template.
=> Updated getting started tutorial

articles/getting_started/packaging_games.md
Fixes #96
We might want to synchronize this update with the 3.8.3 release. It will be misleading otherwise because it needs API present in 3.8.3 only.
=> Update documentation for PublishAot

articles/getting_started/packaging_games.md
Noting that WindowsDX currently doesn't support AOT.
=> WindowsDX note about AOT support

index.md
index.md had a typo in the API reference section
=> fixing typo in index.md

articles/tutorials/building_2d_games/14_soundeffects_and_music/index.md
The 14_soundeffects_and_music page has a link for the `DynamicSoundEffectInstance` docs that actually goes to `SoundEffectInstance` doc page.  This PR corrects that link.
=> Correcting link to DynamicSoundEffectInstance

articles/tutorials/building_2d_games/12_collision_detection/index.md
This was something planned for a later chapter that was adjusted and removed.  This removes the line that mentions it will be in a later chapter.
=> Remove spatial hashing mention

docfx.json, errors/setupwine/index.md, templates/monogame/conceptual.extension.js, templates/monogame/layout/_master.tmpl, templates/monogame/partials/redirect.tmpl.partial
This PR implements a redirect system for MonoGame error documentation links.  The system allows us to create stable, short URLs that can be updated without breaking external references, similar to URL shorteners.
**How it works**:
- Create a redirect page in the `/errors/` directory such as `/errors/setupwine/index.md`
- The page generates a clean URL: `https://docs.monogame.net/errors/setupwine`
- When accessed, it automatically redirects to the target documentation.
- If the target changes only the redirect value needs to be updated.
**Example Usage**
```md
---
redirect: ./path/to/target/index.md
---
[redirect](./path/to/target.md]
```
> [!NOTE]
> Due to DocFX's document processing limitations, the redirect URL must appear both in the front matter and as a link in the document body. By …
=> Add Redirect Feature or Error Documentation Links

articles/getting_started/1_setting_up_your_os_for_development_macos.md, articles/tutorials/building_2d_games/02_getting_started/index.md
We need to add the following command for wine for it to run
```
xattr -dr com.apple.quarantine "/Applications/Wine Stable.app"
```
=> Add additional command for wine

articles/getting_started/1_setting_up_your_os_for_development_macos.md, articles/getting_started/1_setting_up_your_os_for_development_ubuntu.md, articles/getting_started/1_setting_up_your_os_for_development_windows.md, articles/getting_started/2_choosing_your_ide_vscode.md
This is to address issue #111  and also addresses half of #90 
Update the OS specific docs to include install instructions for the maui workload (as well as a tab to install android, ios, and maui altogether).
Updated the VS code doc to explain the benefits of installing the .NET MAUI extension to make debugging mobile games possible.
I do not have any better suggestions for replacing the Xamarin docs for the second part of issue #90 though. So hopefully resolving half the issue is good enough for now ;)
=> Add information on maui requirements for mobile debugging

articles/tutorials/building_2d_games/12_collision_detection/index.md, articles/tutorials/building_2d_games/12_collision_detection/snippets/vector2_distance.cs
The _Building 2D Games_ tutorial is amazing! I really appreciate the hard work that went into it. I went through Chapter 12 and everything was great until the circle collision explanation. There's a couple of errors pertaining to the direction of inequality sign, so this MR attempts to straighten it out. It's notable that the `Circle` class is implemented correctly later in this chapter (see `./snippets/cirlce.cs#methods_intersects`).
=> Tutorial - Building 2D Games - Fix circle collision math and a few typos.

articles/samples.md, index.md
Cleaned up landing page to include:
- Docs
- API
- Tutorials
- Samples (added)
Updated samples page with the same BIG buttons.
=> Updated samples page

articles/tutorials/building_2d_games/05_content_pipeline/index.md
Fixed a spelling mistake in Chapter 5 of the Building 2D games tutorial.
=> For Issue #158 Spelling Mistake In Building 2D Games Tutorial Chapter 5 - ContentManager Methods

articles/tutorials/building_2d_games/11_input_management/index.md, articles/tutorials/building_2d_games/11_input_management/snippets/core.cs, articles/tutorials/building_2d_games/11_input_management/snippets/game1.cs, articles/tutorials/building_2d_games/12_collision_detection/index.md, articles/tutorials/building_2d_games/12_collision_detection/snippets/game1.cs, articles/tutorials/building_2d_games/13_working_with_tilemaps/index.md, articles/tutorials/building_2d_games/13_working_with_tilemaps/snippets/game1.cs, articles/tutorials/building_2d_games/14_soundeffects_and_music/index.md, articles/tutorials/building_2d_games/14_soundeffects_and_music/snippets/game1.cs, articles/tutorials/building_2d_games/15_audio_controller/index.md, articles/tutorials/building_2d_games/15_audio_controller/snippets/core.cs, articles/tutorials/building_2d_games/15_audio_controller/snippets/game1.cs, articles/tutorials/building_2d_games/16_working_with_spritefonts/index.md, articles/tutorials/building_2d_games/16_working_with_spritefonts/snippets/game1.cs, articles/tutorials/building_2d_games/17_scenes/index.md, articles/tutorials/building_2d_games/17_scenes/snippets/core.cs
This pull request addresses community feedback regarding missing ExitOnEscape functionality after following the input management tutorial, where removing the old input handling code inadvertently disabled the escape key exit behavior.
Resolves: [Issue #142](https://github.com/MonoGame/docs.monogame.github.io/issues/142)
Updated the input management tutorial to maintain consistent ExitOnEscape behavior by:
- **Added ExitOnEscape initialization in Core constructor**: Set ExitOnEscape = true; in the Core.cs constructor to mimic the default MonoGame template behavior
- **Removed outdated input handling code**: Eliminated the legacy GamePad.GetState() and Keyboard.GetState().IsKeyDown(Keys.Escape) checks from all Game1.cs snippet files throughout the tutorial
=> Fix ExitOnEscape behavior inconsistency in input management tutorial

articles/tutorials/building_2d_games/20_implementing_ui_with_gum/index.md
This pull request addresses community feedback regarding confusing terminology in Chapter 20's explanation of Gum's core concepts.
Resolves: [Issue #143](https://github.com/MonoGame/docs.monogame.github.io/issues/143)
Updated the "Forms and Visuals" section in "Chapter 20: Implementing UI with Gum" to eliminate terminology confusion by:
- **Replaced "objects" terminology**: Changed from "Gum provides two types of objects" to "Two concepts are important when working with Gum" to avoid OOP confusion
- **Enhanced Visual explanation**: Added clarification about the *Runtime suffix naming convention and specific examples of Visual elements
- **Restructured content flow**: Moved the explanation of Forms controls' `Visual` property relationship outside bullet points for clearer logical …
=> Remove Confusing "Objects" Terminology from Gum Forms and Visuals Section

articles/tutorials/building_2d_games/12_collision_detection/index.md, articles/tutorials/building_2d_games/12_collision_detection/snippets/game1.cs, articles/tutorials/building_2d_games/13_working_with_tilemaps/index.md, articles/tutorials/building_2d_games/13_working_with_tilemaps/snippets/game1.cs, articles/tutorials/building_2d_games/14_soundeffects_and_music/index.md, articles/tutorials/building_2d_games/14_soundeffects_and_music/snippets/game1.cs, articles/tutorials/building_2d_games/15_audio_controller/index.md, articles/tutorials/building_2d_games/15_audio_controller/snippets/game1.cs, articles/tutorials/building_2d_games/16_working_with_spritefonts/index.md, articles/tutorials/building_2d_games/16_working_with_spritefonts/snippets/game1.cs, articles/tutorials/building_2d_games/17_scenes/snippets/gamescene.cs, articles/tutorials/building_2d_games/22_snake_game_mechanics/snippets/bat/bounce.cs
Normalizes the vector before calculating the reflection for the bat bounce in the 2D tutorial
- Closes: #172 
- https://github.com/MonoGame/MonoGame.Samples/issues/96
=> Normalize vector before reflecting for bat bounce.

.github/workflows/main.yml, .github/workflows/pullrequest.yml, README.md, build.ps1, build.sh, ci.docfx.json, docfx.json, serve.ps1, serve.sh
This PR resolves documentation build failures by updating DocFX configuration to use pre-built assemblies instead of building from source. Previously, native build failures in both local environments and GitHub workflows prevented complete documentation generation with valid cross-reference links.
DocFX was attempting to build MonoGame projects from source during documentation generation, which failed due to native build dependencies. This resulted in:
- Incomplete API documentation
- Broken cross-reference links
Configure DocFX to reference pre-built assemblies directly, bypassing the native build process while maintaining complete API documentation coverage.
- **Updated `docfx.json`**: Modified configuration to reference `MonoGame.Framework.dll` and …
=> Prebuild Assemblies And Reference Them For Documentation Builds

articles/tutorials/building_2d_games/07_optimizing_texture_rendering/index.md
Fixed grammar typo where `here is are` was used.
=> Fix grammar in Pong game draw calls example
